# Generated by Django 2.2.16 on 2022-04-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220422_2158'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_name',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_following'),
        ),
    ]
